name:  CI

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build-dot-net:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9'
            dotnet-quality: 'ga'

        - name: Restore dependencies
          run: dotnet restore ./dotnet/PuzzleSolver.sln

        - name: Build project
          run: dotnet build --configuration Release --no-restore ./dotnet/PuzzleSolver.sln

        - name: Run tests
          run: dotnet test --configuration Release --no-build --verbosity normal ./dotnet/PuzzleSolver.sln

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        
        - name: Build and push
          uses: docker/build-push-action@v6
          if: false
          with:
            context: ./dotnet
            file: ./dotnet/Dockerfile
            push: true
            tags: newmancodes/puzzle-solver:dotnet-latest
    
    build-python:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
    build-typescript:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
